---
plugin: amazon.aws.aws_ec2
regions:
  - us-east-1  
filters:
  tag:Deployment: Ansible  
keyed_groups:
  - key: tags.Name
    prefix: tag
hostnames:
  - tag:Name
compose:
  ansible_host: public_ip_address  # or private_ip_address if using a VPC