---
- name: Install and verify Apache Web Server on Amazon Linux
  hosts: tag_Ansible
  become: yes
  gather_facts: True
  
  vars:
    ansible_user : ec2-user 
    ansible_ssh_private_key_file : ~/.ssh/linux.pem
    image_source: ~/images/sample.jpg
    image_dest: /var/www/html/sample.jpg
    source_file: ~/html/index.html
    dest_file: /var/www/html/index.html
  
  pre_tasks:
    - name: Print tag_Ansible group
      debug:
        msg: "Hosts in tag_Ansible group: {{ groups['tag_Ansible'] }}"

    - name: Print individual host details
      debug:
        msg: "Host: {{ inventory_hostname }}, IP: {{ ansible_host }}"
      when: inventory_hostname in groups['tag_Ansible']
  tasks:
    - name: Install Apache on Amazon Linux
      yum:
        name: httpd
        state: latest

    - name: Start and enable Apache service on Amazon Linux
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Wait for Apache to start
      wait_for:
        port: 80
        state: started
        delay: 5
        timeout: 30
    
    - name: Copy index.html
      copy:
        src: "{{ source_file }}"
        dest: "{{ dest_file }}"
        mode: '0555'
      notify: Restart Httpd
      
    - name: Copy Image file
      copy:
        src: "{{ image_source }}"
        dest: "{{ image_dest }}"
        mode: '0644'
      notify: Restart Httpd
      
    
  handlers:
    - name: Restart Httpd
      service:
        name: httpd
        state: restarted
