name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1  # Replace with your desired AWS region

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Replace with your desired Terraform version

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform/

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform/
        env:
          TF_VAR_some_variable: ${{ secrets.TF_VAR_SOME_VARIABLE }}  # Replace with any environment variables required by your Terraform configuration

      - name: Terraform Approval
        run: echo "No approval step required"  # You might want to implement a manual approval step or another mechanism for approval
      
      - name: Set up Ansible
        uses: ansible/ansible-runner@v2
        with:
          version: 2.14  # Replace with your desired Ansible version

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/myplaybook.yml -i ansible/hosts.txt
        working-directory: ./